### ISSUE TITLE
tox -e functional fails TestWorker.test_workers_ping test.

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/tetra#26]
Please see https://gist.github.com/sam-falvo/577d961e1537747186644147cc140448 for a listing of the Python traceback I'm getting when running the `tox -e functional` tests.

Not quite sure how to fix this on my own.  Any guidance would be appreciated.  Thanks!

**Comment by pglass** [comment]
Tetra has an api node and a worker node (well, at least one of each). That test just tries to ping the worker node to see if it's up. The worker node is a celery worker, and the api/worker communicate across a queue (rabbitmq).

I would check if the queue and worker containers are up and running. A `make docker-dev` only starts the api and worker, while `make docker-db` and `make docker-queue` start the database and rabbitmq containers.

I forget why these are separated, but the README doesn't mention those extra steps so we should probably add that to the README.
